discourse_post_folding:
  discourse_post_folding_enabled:
    default: false
    client: true
  discourse_post_folding_can_fold_post_groups:
    default: "1|2|3|14" # by order: @admin, @moderators, @staff, @trust_level_4
    client: false
    type: group_list
    list_type: compact
    allow_any: false
